version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    expose:
     - 3306
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    volumes:
     - mysql_data:/var/lib/mysql
  wordpress:
    image: wordpress
    restart: always
    depends_on:
     - db
    ports:
     - "80:80"
    environment:
     - "WORDPRESS_DB_HOST=db:3306"
     - "WORDPRESS_DB_NAME=$MYSQL_DATABASE"
     - "WORDPRESS_DB_USER=$MYSQL_USER"
     - "WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD"
     #- VIRTUAL_HOST
     #- LETSENCRYPT_HOST
     #- LETSENCRYPT_EMAIL
    volumes:
     - ./backup:/backup
     - wordpress_files:/var/www/html
  backup:
    #image: tonanuvem/wordpress-backup
    image: tonanuvem/wordpress-backup:20201008_0245
    restart: always
    volumes:
     - ./backup:/backup
     - wordpress_files:/var/www/html
    depends_on:
     - db
    environment:
     - "MYSQL_ENV_MYSQL_HOST=db"
     - "MYSQL_ENV_MYSQL_DATABASE=$MYSQL_DATABASE"
     - "MYSQL_ENV_MYSQL_USER=$MYSQL_USER"
     - "MYSQL_ENV_MYSQL_PASSWORD=$MYSQL_PASSWORD"
     - "MYSQL_PORT_3306_TCP_PORT=3306"
volumes:
  mysql_data:
  wordpress_files:
